### ISSUE TITLE
Multi Word Expressions

### ISSUE THREAD

**Issue by apmoore1** [UCREL/pymusas#24]
To incorporate Multi Word Expressions (MWE) into the [USAS Rule Based Tagger](https://ucrel.github.io/pymusas/api/taggers/rule_based#usasrulebasedtagger). The MWEs will come from MWE lexicons, of which examples of these can be found in the [Multilingual USAS GitHub repository](https://github.com/UCREL/Multilingual-USAS#multi-word-expression-mwe-lexicon-file-format), e.g. the [Spanish MWE lexicon](https://github.com/UCREL/Multilingual-USAS/blob/master/Spanish/mwe-es.tsv).

## Tasks

- [ ] Define the MWE template. Within the MWE lexicons are MWE templates, these templates are a pattern matching syntax (like a regular expression) that when matched define a MWE and the semantic tags associated with the MWE. However, there is no concrete definition for this syntax that is used for MWE templates, thus this is the first task. **Partially completed**, an initial definition of this syntax can be found [here.](https://github.com/UCREL/pymusas/blob/mwe/docs/docs/usage/notes/mwe_syntax.md)
- [ ] Incorporate MWE templates that do not have a special syntax, e.g. all templates that do not use the wildcard (`*`) or curly brace syntax (`{}`).
- [ ] Incorporate MWE templates that use the wildcard (`*`) special syntax.
- [ ] Incorporate MWE templates that use the curly brace (`{}`) special syntax, which cover discontinuous MWE's.
